### ISSUE TITLE
how to get the stack info when receive evnet?

### ISSUE THREAD

**Issue by chena1982** [microsoft/krabsetw#26]
It seems need set EVENT_ENABLE_PROPERTY_STACK_TRACE when call EnabeTraceEx2.
but i can't see any api to enbale this.
Thanks.

**Comment by zacbrown** [comment]
Hi,

Could you provide some sample code and an explanation for what you're trying to do?

Thanks,

Zac

**Comment by chena1982** [comment]
```
	PEVENT_FILTER_EVENT_ID filterId;
	DWORD size = FIELD_OFFSET(EVENT_FILTER_EVENT_ID, Events[2]);
	filterId = (PEVENT_FILTER_EVENT_ID)new BYTE[size];
	filterId->FilterIn = TRUE;
	filterId->Count = 2;
	filterId->Events[0] = 0x2b;
	filterId->Events[1] = 0x21;


	EVENT_FILTER_DESCRIPTOR filterDesc;
	ZeroMemory(&filterDesc, sizeof(filterDesc));
	filterDesc.Ptr = (ULONGLONG)filterId;
	filterDesc.Size = size;
	filterDesc.Type = EVENT_FILTER_TYPE_STACKWALK;

	ENABLE_TRACE_PARAMETERS traceParam;
	ZeroMemory(&traceParam, sizeof(traceParam));
	traceParam.Version = ENABLE_TRACE_PARAMETERS_VERSION_2;
	traceParam.EnableProperty = EVENT_ENABLE_PROPERTY_STACK_TRACE;
	traceParam.SourceId = guid[(int)type];
	traceParam.EnableFilterDesc = &filterDesc;
	traceParam.FilterDescCount = 1;


	_status = EnableTraceEx2(hSession, &guid[(int)type], EVENT_CONTROL_CODE_ENABLE_PROVIDER, level, anyKeyword, allKeyword, 0, &traceParam);
```

some code to enable stack trace info.

**Comment by zacbrown** [comment]
Hi,

We can look into making the parameters more configurable. I'll make a bug. It will likely be a month before we make the change as we finish out our planning cycle for this quarter.

-Zac

**Comment by zacbrown** [comment]
I've implemented the ability to set  EVENT_ENABLE_PROPERTY_STACK_TRACE for the trace_flags on a given provider object. I did not expose this functionality in the .NET layer. It's only available in the native krabsetw API.

Additionally, it was non-trivial to add support for EVENT_FILTER_DESCRIPTOR so I do not support EVENT_FILTER_DESCRIPTOR with EVENT_FILTER_TYPE_STACKWALK.

**Comment by chena1982** [comment]
I call the function trace_flags(EVENT_ENABLE_PROPERTY_STACK_TRACE), but still can't get the stack info, eventRecord.ExtendedDataCount is always zero.

```
#include "stdafx.h"
#include "krabs.hpp"
using namespace krabs;

DEFINE_GUID( /* 222962AB-6180-4B88-A825-346B75F2A24A */
    HeapTraceGuid,
    0x222962AB,
    0x6180,
    0x4B88,
    0xa8, 0x25, 0x34, 0x6b, 0x75, 0xf2, 0xa2, 0x4a
);

void mycallbackFunction(const EVENT_RECORD & eventRecord)
{
    auto & header = eventRecord.EventHeader;

    if (header.ProviderId != HeapTraceGuid)
    {
        return;
    }

    LPWSTR pszPropertyName = NULL;
    PEVENT_HEADER_EXTENDED_DATA_ITEM pExtendedData;

    for (DWORD index = 0; index < eventRecord.ExtendedDataCount; index++)
    {
        wprintf(L"\t--- EVENT_PROPERTY_INFO ---\n");
        pExtendedData = &eventRecord.ExtendedData[index];
        switch (pExtendedData->ExtType)
        {
        case EVENT_HEADER_EXT_TYPE_STACK_TRACE32:
            break;
            case
                EVENT_HEADER_EXT_TYPE_STACK_TRACE64:
                    break;
        }
    }
}





int main()
{
    user_trace memoryCheck(L"MemoryCheck");

    //provider<> heapProvider(L"{222962AB-6180-4B88-A825-346B75F2A24A}");
    provider<> heapProvider(L"Heap Trace Provider");
    heapProvider.any(0x2b);
    heapProvider.any(0x21);

    heapProvider.trace_flags(EVENT_ENABLE_PROPERTY_STACK_TRACE);

    heapProvider.add_on_event_callback(mycallbackFunction);

    memoryCheck.enable(heapProvider);

    memoryCheck.start();

    system("PAUSE");

    memoryCheck.stop();

    return 0;
}
```
i don't how to get the stack, can you give some suggestion, or add a sample?
thanks.

**Comment by zacbrown** [comment]
Unfortunately I'm not very familiar with how to use that functionality. We don't currently use it within our own team due to performance concerns.

I'll do some testing on my side and see if I can reproduce the issue you're seeing.

**Comment by zacbrown** [comment]
So looking at this - it may be necessary to use the `EVENT_FILTER_DESCRIPTOR` type within the code.

Unfortunately - that's a non-trivial change for krabsetw since we don't use the native TDH filtering mechanism (`EVENT_FILTER_DESCRIPTOR`) and instead have built our own.

If this is an important scenario, please let me know and I can add it as a backlog item but I'm not sure when it'll get implemented.

**Comment by pathtofile** [comment]
Hey @chena1982 - Is this still an issue for you in 2020? I jsut ran the following code, and was able to now get stack traces:
```c++
    // Setup basic Microsoft-Windows-Kernel-Process trace
    krabs::user_trace trace(L"My magic trace");
    krabs::provider<> provider(krabs::guid(L"{22FB2CD6-0E7B-422B-A0C7-2FAD1FD0E716}"));
    provider.any(0x10);
    // Enable Stack Trace
    provider.trace_flags(EVENT_ENABLE_PROPERTY_STACK_TRACE);

    // Print stack traces for ID 1 events, i.e. Process Starts
    // You can confirm the stack values by running ProcMon at the same time
    krabs::event_filter filter(krabs::predicates::id_is(1));
    filter.add_on_event_callback([](const EVENT_RECORD &record, const krabs::trace_context &trace_context) {
        // Get Stack trace from events
        krabs::schema schema(record, trace_context.schema_locator);
        for (USHORT i = 0; i < record.ExtendedDataCount; i++)
        {
            EVENT_HEADER_EXTENDED_DATA_ITEM data_item = record.ExtendedData[i];

            // Made assumtion here it's a 64-bit trace
            PEVENT_EXTENDED_ITEM_STACK_TRACE64 pst64 = (PEVENT_EXTENDED_ITEM_STACK_TRACE64)data_item.DataPtr;
            uint32_t size = (data_item.DataSize - sizeof(ULONG64)) / sizeof(ULONG64);
            wprintf(L"Stack Trace Size: %d \n", size);
            for (size_t x = 0; x < size; x++)
            {
                ULONG64 addr = pst64->Address[x];
                printf("Stack Trace addr: 0x%llx\n", addr);
            }
            printf("--------------------------\n");
        }
    });

    // Start ETW Session
    provider.add_filter(filter);
    trace.enable(provider);
    printf("Starting trace...\n");
    trace.start();
```
(This is just sample code to prove it works and is misisng a lot of edge cases)

**Comment by swannman** [comment]
If we wanted to add native support to this in the API, we could do something like #125 : https://github.com/microsoft/krabsetw/commit/dc92c87460d0205528b59415e5281c53ca6d13ae

**Comment by jdu2600** [comment]
https://github.com/microsoft/krabsetw/pull/191 - proposed stack trace helpers

**Comment by swannman** [comment]
Resolved by #191, thank you @jdu2600 !
